DELETE FROM users;

ALTER TABLE users DROP COLUMN full_name;
ALTER TABLE users ADD COLUMN name VARCHAR(50) NOT NULL;
ALTER TABLE users ADD COLUMN surname VARCHAR(50) NOT NULL;
ALTER TABLE users ADD COLUMN patronymic VARCHAR(50);
ALTER TABLE users ADD CONSTRAINT uq_email UNIQUE (email);
ALTER TABLE users ALTER COLUMN email SET NOT NULL;
